# coding: utf-8

VERSION_MAJOR = 3
VERSION_MINOR = 1
VERSION_BUILD = 13
VERSION_INFO = (VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD)
VERSION_STRING = "%d.%d.%d" % VERSION_INFO

__version__ = VERSION_INFO