# coding: utf-8

VERSION_MAJOR = 2
VERSION_MINOR = 0
VERSION_BUILD = 8
VERSION_INFO = (VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD)
VERSION_STRING = "%d.%d.%d" % VERSION_INFO

VERSIONS = ["2.0.0", "2.0.1", "2.0.2", "2.0.3", "2.0.4", "2.0.5", "2.0.6", "2.0.7"]
__version__ = VERSION_INFO